// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Kritsana135/assessment/domain"
	mock "github.com/stretchr/testify/mock"
)

// ExpenseRepository is an autogenerated mock type for the ExpenseRepository type
type ExpenseRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, expense
func (_m *ExpenseRepository) Create(ctx context.Context, expense *domain.ExpenseTable) error {
	ret := _m.Called(ctx, expense)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ExpenseTable) error); ok {
		r0 = rf(ctx, expense)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetExpenses provides a mock function with given fields: ctx
func (_m *ExpenseRepository) GetExpenses(ctx context.Context) ([]domain.ExpenseTable, error) {
	ret := _m.Called(ctx)

	var r0 []domain.ExpenseTable
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ExpenseTable); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ExpenseTable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpensesById provides a mock function with given fields: ctx, id
func (_m *ExpenseRepository) GetExpensesById(ctx context.Context, id uint64) (domain.ExpenseTable, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.ExpenseTable
	if rf, ok := ret.Get(0).(func(context.Context, uint64) domain.ExpenseTable); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.ExpenseTable)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateExpense provides a mock function with given fields: ctx, id, expense
func (_m *ExpenseRepository) UpdateExpense(ctx context.Context, id uint64, expense *domain.ExpenseTable) error {
	ret := _m.Called(ctx, id, expense)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, *domain.ExpenseTable) error); ok {
		r0 = rf(ctx, id, expense)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewExpenseRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewExpenseRepository creates a new instance of ExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExpenseRepository(t mockConstructorTestingTNewExpenseRepository) *ExpenseRepository {
	mock := &ExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
